// ── Herb Data ─────────────────────────────────────────────────────────────
// Static herb data is also stored in Supabase (static_herbs table).
// Loaded at runtime via sbFetchStaticHerbs(). This is the fallback.
export const HERBS_FALLBACK = [
  {
    id: 1,
    name: "Ashwagandha",
    latinName: "Withania somnifera",
    emoji: "🌿",
    family: "Solanaceae",
    origin: "India, North Africa",
    partUsed: "Root, berries",
    category: "Adaptogen",
    altNames: ["Indian ginseng", "Winter cherry", "Asgandh", "Samm Al Ferakh"],
    description: "A revered herb in Ayurvedic medicine for over 3,000 years, used primarily as an adaptogen to help the body manage stress.",
    uses: ["Stress & anxiety reduction", "Cognitive enhancement", "Athletic performance", "Sleep quality", "Testosterone support"],
    conditions: ["stress-mood", "mind-cognition", "performance", "sleep"],
    papers: [],
  },
  {
    id: 2,
    name: "Turmeric",
    latinName: "Curcuma longa",
    emoji: "🟡",
    family: "Zingiberaceae",
    origin: "South Asia",
    partUsed: "Rhizome",
    category: "Anti-inflammatory",
    altNames: ["Haldi", "Curcuma", "Indian saffron", "Yellow ginger"],
    description: "A golden spice from South Asia with potent anti-inflammatory properties, driven by its active compound curcumin.",
    uses: ["Anti-inflammatory", "Antioxidant", "Joint health", "Digestive support", "Liver protection"],
    conditions: ["inflammation", "digestive", "heart-circulation"],
    papers: [],
  },
  {
    id: 3,
    name: "Valerian",
    latinName: "Valeriana officinalis",
    emoji: "🌸",
    family: "Caprifoliaceae",
    origin: "Europe, Asia",
    partUsed: "Root",
    category: "Sedative",
    altNames: ["Garden valerian", "Garden heliotrope", "All-heal", "Setwall"],
    description: "A flowering plant native to Europe and Asia, traditionally used for its sedative and anxiolytic effects.",
    uses: ["Sleep disorders", "Anxiety", "Restlessness", "Menopausal symptoms", "Headaches"],
    conditions: ["sleep", "stress-mood", "women-health"],
    papers: [],
  },
  {
    id: 4,
    name: "Echinacea",
    latinName: "Echinacea purpurea",
    emoji: "🌺",
    family: "Asteraceae",
    origin: "North America",
    partUsed: "Aerial parts, root",
    category: "Immunomodulator",
    altNames: ["Purple coneflower", "American coneflower", "Hedgehog"],
    description: "Native to North America, long used by indigenous peoples and now one of the most popular herbal supplements for immune support.",
    uses: ["Immune stimulation", "Common cold prevention", "Wound healing", "Anti-viral", "Upper respiratory infections"],
    conditions: ["immune"],
    papers: [],
  },
  {
    id: 5,
    name: "Ginkgo",
    latinName: "Ginkgo biloba",
    emoji: "🍃",
    family: "Ginkgoaceae",
    origin: "China",
    partUsed: "Leaves",
    category: "Nootropic",
    altNames: ["Maidenhair tree", "Fossil tree", "Bai guo", "Kew tree"],
    description: "One of the oldest living tree species on earth, used in traditional Chinese medicine for millennia, known for its effects on circulation and cognition.",
    uses: ["Cognitive function", "Memory enhancement", "Circulation", "Tinnitus", "Anxiety"],
    conditions: ["mind-cognition", "heart-circulation", "stress-mood"],
    papers: [],
  },
  {
    id: 6,
    name: "St. John's Wort",
    latinName: "Hypericum perforatum",
    emoji: "☀️",
    family: "Hypericaceae",
    origin: "Europe",
    partUsed: "Flowers, leaves",
    category: "Antidepressant",
    altNames: ["Klamath weed", "Goatweed", "Tipton's weed", "Rosin rose"],
    description: "A flowering plant used for centuries in European folk medicine, most known for its antidepressant and mood-lifting properties.",
    uses: ["Depression", "Anxiety", "Seasonal affective disorder", "Nerve pain", "Wound healing"],
    conditions: ["stress-mood", "mind-cognition"],
    papers: [],
  },
  {
    id: 7, name: "Rhodiola Rosea", latinName: "Rhodiola rosea",
    family: "Crassulaceae", origin: "Arctic Europe, Asia", partUsed: "Root", category: "Adaptogen",
    altNames: ["Golden root", "Arctic root", "Rose root", "Roseroot"],
    description: "A Scandinavian and Siberian adaptogen used for centuries to enhance mental and physical resilience under extreme conditions.",
    uses: ["Stress adaptation", "Mental fatigue", "Physical endurance", "Mood support", "Cognitive performance"],
    conditions: ["stress-mood", "mind-cognition", "performance"], papers: [],
  },
  {
    id: 8, name: "Lion's Mane", latinName: "Hericium erinaceus",
    family: "Hericiaceae", origin: "North America, Europe, Asia", partUsed: "Fruiting body, mycelium", category: "Nootropic",
    altNames: ["Yamabushitake", "Monkey head mushroom", "Bearded tooth fungus", "Satyr's beard"],
    description: "A medicinal mushroom with unique neuroprotective properties, shown to stimulate nerve growth factor (NGF) synthesis.",
    uses: ["Nerve regeneration", "Cognitive enhancement", "Memory", "Anxiety", "Gut health"],
    conditions: ["mind-cognition", "digestive"], papers: [],
  },
  {
    id: 9, name: "Bacopa", latinName: "Bacopa monnieri",
    family: "Plantaginaceae", origin: "India, Southeast Asia", partUsed: "Whole plant", category: "Nootropic",
    altNames: ["Brahmi", "Water hyssop", "Herb of grace", "Thyme-leafed gratiola"],
    description: "A staple of Ayurvedic medicine for over 3,000 years, traditionally used to enhance memory, learning, and cognitive endurance.",
    uses: ["Memory consolidation", "Learning", "Anxiety reduction", "Neuroprotection", "ADHD support"],
    conditions: ["mind-cognition", "stress-mood"], papers: [],
  },
  {
    id: 10, name: "Ginger", latinName: "Zingiber officinale",
    family: "Zingiberaceae", origin: "Southeast Asia", partUsed: "Rhizome", category: "Digestive",
    altNames: ["Common ginger", "Canton ginger", "Adrak", "Sheng jiang"],
    description: "One of the most widely used medicinal spices globally, with broad actions across the digestive, immune, and inflammatory systems.",
    uses: ["Nausea", "Digestive comfort", "Anti-inflammatory", "Immune support", "Circulation"],
    conditions: ["digestive", "inflammation", "immune", "heart-circulation"], papers: [],
  },
  {
    id: 11, name: "Holy Basil", latinName: "Ocimum tenuiflorum",
    family: "Lamiaceae", origin: "India", partUsed: "Leaves, stems, seeds", category: "Adaptogen",
    altNames: ["Tulsi", "Sacred basil", "Hot basil", "Krapao"],
    description: "Revered in Ayurveda as the Queen of Herbs, Tulsi is a primary adaptogen with broad immunomodulatory and metabolic effects.",
    uses: ["Stress adaptation", "Blood sugar regulation", "Immune support", "Respiratory health", "Anti-inflammatory"],
    conditions: ["stress-mood", "immune", "metabolic"], papers: [],
  },
  {
    id: 12, name: "Elderberry", latinName: "Sambucus nigra",
    family: "Adoxaceae", origin: "Europe, North Africa", partUsed: "Berries, flowers", category: "Immunomodulator",
    altNames: ["European elderberry", "Black elder", "Sambucus", "Holunder"],
    description: "A traditional European remedy for colds and flu, now backed by clinical evidence for its antiviral and immune-modulating properties.",
    uses: ["Cold and flu prevention", "Antiviral", "Immune stimulation", "Inflammation reduction", "Upper respiratory health"],
    conditions: ["immune", "inflammation"], papers: [],
  },
  {
    id: 13, name: "Milk Thistle", latinName: "Silybum marianum",
    family: "Asteraceae", origin: "Mediterranean region", partUsed: "Seeds", category: "Hepatoprotective",
    altNames: ["Blessed milk thistle", "Marian thistle", "Mary thistle", "Silymarin"],
    description: "The world's most researched liver-protective herb, containing the flavonoid silymarin which shields and regenerates liver cells.",
    uses: ["Liver protection", "Liver detoxification", "Antioxidant", "Cholesterol support", "Gallbladder health"],
    conditions: ["digestive", "heart-circulation"], papers: [],
  },
  {
    id: 14, name: "Chamomile", latinName: "Matricaria chamomilla",
    family: "Asteraceae", origin: "Europe, Western Asia", partUsed: "Flowers", category: "Nervine",
    altNames: ["German chamomile", "Blue chamomile", "Wild chamomile", "Manzanilla"],
    description: "One of the most consumed medicinal teas globally, with well-documented anxiolytic and sleep-promoting properties.",
    uses: ["Sleep support", "Anxiety", "Digestive cramping", "Anti-inflammatory", "Stress"],
    conditions: ["sleep", "stress-mood", "digestive"], papers: [],
  },
  {
    id: 15, name: "Lavender", latinName: "Lavandula angustifolia",
    family: "Lamiaceae", origin: "Mediterranean", partUsed: "Flowers, essential oil", category: "Nervine",
    altNames: ["True lavender", "English lavender", "Garden lavender", "Common lavender"],
    description: "A fragrant shrub whose extracts have demonstrated anxiolytic effects comparable to low-dose benzodiazepines in clinical trials.",
    uses: ["Anxiety", "Sleep quality", "Stress", "Headaches", "Mood"],
    conditions: ["sleep", "stress-mood"], papers: [],
  },
  {
    id: 16, name: "Peppermint", latinName: "Mentha × piperita",
    family: "Lamiaceae", origin: "Europe, Middle East", partUsed: "Leaves, essential oil", category: "Digestive",
    altNames: ["Brandy mint", "Balm mint", "Lamb mint", "Curled mint"],
    description: "A hybrid mint with potent antispasmodic activity, widely used for irritable bowel syndrome and upper gastrointestinal complaints.",
    uses: ["IBS", "Bloating", "Nausea", "Headaches", "Mental focus"],
    conditions: ["digestive", "mind-cognition"], papers: [],
  },
  {
    id: 17, name: "Hawthorn", latinName: "Crataegus monogyna",
    family: "Rosaceae", origin: "Europe, Asia, North America", partUsed: "Berries, leaves, flowers", category: "Cardiotonic",
    altNames: ["Common hawthorn", "May tree", "White thorn", "Quickthorn"],
    description: "A thorny shrub with centuries of use as a cardiac tonic, supported by clinical evidence for blood pressure and mild heart failure.",
    uses: ["Blood pressure", "Heart failure support", "Circulation", "Cholesterol", "Anxiety"],
    conditions: ["heart-circulation", "stress-mood"], papers: [],
  },
  {
    id: 18, name: "Garlic", latinName: "Allium sativum",
    family: "Amaryllidaceae", origin: "Central Asia", partUsed: "Bulb", category: "Antimicrobial",
    altNames: ["Common garlic", "Stinking rose", "Ajo", "Lasun"],
    description: "One of the most studied medicinal plants in history, with broad antimicrobial, cardiovascular, and metabolic effects driven by allicin.",
    uses: ["Blood pressure", "Cholesterol", "Immune support", "Antimicrobial", "Blood sugar"],
    conditions: ["immune", "heart-circulation", "metabolic"], papers: [],
  },
  {
    id: 19, name: "Cinnamon", latinName: "Cinnamomum verum",
    family: "Lauraceae", origin: "Sri Lanka", partUsed: "Bark", category: "Metabolic",
    altNames: ["Ceylon cinnamon", "True cinnamon", "Sri Lanka cinnamon", "Kurundu"],
    description: "Beyond its culinary use, Ceylon cinnamon has well-documented effects on insulin sensitivity and blood glucose regulation.",
    uses: ["Blood sugar regulation", "Insulin sensitivity", "Anti-inflammatory", "Antimicrobial", "Cholesterol"],
    conditions: ["metabolic", "inflammation", "heart-circulation"], papers: [],
  },
  {
    id: 20, name: "Fenugreek", latinName: "Trigonella foenum-graecum",
    family: "Fabaceae", origin: "India, Mediterranean", partUsed: "Seeds, leaves", category: "Metabolic",
    altNames: ["Methi", "Greek hay", "Bird's foot", "Hulba"],
    description: "A culinary and medicinal seed used across Ayurveda and Unani medicine for its effects on blood sugar, hormones, and lactation.",
    uses: ["Blood sugar", "Testosterone support", "Milk production", "Cholesterol", "Digestive health"],
    conditions: ["metabolic", "performance", "women-health", "digestive"], papers: [],
  },
  {
    id: 21, name: "Vitex", latinName: "Vitex agnus-castus",
    family: "Lamiaceae", origin: "Mediterranean, Central Asia", partUsed: "Berries, leaves", category: "Hormonal",
    altNames: ["Chaste tree", "Chasteberry", "Monk's pepper", "Abraham's balm"],
    description: "The leading herbal medicine for female hormonal balance, with evidence for PMS, menstrual irregularity, and luteal phase support.",
    uses: ["PMS", "Menstrual irregularity", "Hormonal balance", "Breast tenderness", "Fertility"],
    conditions: ["women-health"], papers: [],
  },
  {
    id: 22, name: "Black Cohosh", latinName: "Actaea racemosa",
    family: "Ranunculaceae", origin: "North America", partUsed: "Root, rhizome", category: "Hormonal",
    altNames: ["Black snakeroot", "Bugbane", "Squawroot", "Fairy candle"],
    description: "A North American woodland plant used by indigenous peoples and now the most studied herb for menopausal symptom relief.",
    uses: ["Menopausal symptoms", "Hot flashes", "Night sweats", "Mood", "Sleep disturbance"],
    conditions: ["women-health", "sleep", "stress-mood"], papers: [],
  },
  {
    id: 23, name: "Boswellia", latinName: "Boswellia serrata",
    family: "Burseraceae", origin: "India, Middle East, Africa", partUsed: "Resin", category: "Anti-inflammatory",
    altNames: ["Indian frankincense", "Salai", "Shallaki", "Olibanum"],
    description: "The resin of this tree yields boswellic acids — potent 5-LOX inhibitors with strong clinical evidence in arthritis and IBD.",
    uses: ["Osteoarthritis", "Rheumatoid arthritis", "Inflammatory bowel disease", "Asthma", "Anti-inflammatory"],
    conditions: ["inflammation"], papers: [],
  },
  {
    id: 24, name: "Devil's Claw", latinName: "Harpagophytum procumbens",
    family: "Pedaliaceae", origin: "Southern Africa", partUsed: "Tuberous root", category: "Anti-inflammatory",
    altNames: ["Grapple plant", "Wood spider", "Sengaparile", "Harpago"],
    description: "A root from the Kalahari desert with significant anti-inflammatory and analgesic activity, particularly for musculoskeletal pain.",
    uses: ["Back pain", "Arthritis", "Joint inflammation", "Muscle pain", "Digestive support"],
    conditions: ["inflammation", "digestive"], papers: [],
  },
  {
    id: 25, name: "Tongkat Ali", latinName: "Eurycoma longifolia",
    family: "Simaroubaceae", origin: "Malaysia, Indonesia", partUsed: "Root", category: "Adaptogen",
    altNames: ["Malaysian ginseng", "Pasak bumi", "Longjack", "Ali's umbrella"],
    description: "A Malaysian root with the highest clinical evidence for testosterone support and athletic performance of any botanical.",
    uses: ["Testosterone support", "Sexual function", "Athletic performance", "Stress", "Energy"],
    conditions: ["performance", "stress-mood"], papers: [],
  },
  {
    id: 26, name: "Cordyceps", latinName: "Cordyceps sinensis",
    family: "Ophiocordycipitaceae", origin: "Tibetan Plateau, China", partUsed: "Fruiting body, mycelium", category: "Adaptogen",
    altNames: ["Caterpillar fungus", "Dong chong xia cao", "Yartsa gunbu", "Himalayan gold"],
    description: "A parasitic fungus from the Himalayas used in Traditional Chinese Medicine for 1,500 years to enhance stamina and oxygen utilisation.",
    uses: ["Athletic endurance", "VO2 max", "Immune modulation", "Anti-fatigue", "Sexual function"],
    conditions: ["performance", "immune"], papers: [],
  },
  {
    id: 27, name: "Astragalus", latinName: "Astragalus membranaceus",
    family: "Fabaceae", origin: "China, Mongolia", partUsed: "Root", category: "Immunomodulator",
    altNames: ["Huang qi", "Milk vetch", "Chinese astragalus", "Bei qi"],
    description: "A fundamental herb in Traditional Chinese Medicine and one of the most studied immunomodulators, with emerging evidence in longevity research.",
    uses: ["Immune enhancement", "Fatigue", "Anti-aging", "Cardiovascular", "Blood sugar"],
    conditions: ["immune", "metabolic", "heart-circulation"], papers: [],
  },
  {
    id: 28, name: "Passionflower", latinName: "Passiflora incarnata",
    family: "Passifloraceae", origin: "North America, Central America", partUsed: "Aerial parts", category: "Nervine",
    altNames: ["Maypop", "Purple passionflower", "Wild apricot", "Apricot vine"],
    description: "A vine native to the Americas with evidence-based anxiolytic and hypnotic activity, particularly for generalised and pre-operative anxiety.",
    uses: ["Anxiety", "Sleep onset", "Insomnia", "Restlessness", "Nerve pain"],
    conditions: ["sleep", "stress-mood"], papers: [],
  },
  {
    id: 29, name: "Gotu Kola", latinName: "Centella asiatica",
    family: "Apiaceae", origin: "India, Sri Lanka, China", partUsed: "Whole plant", category: "Nootropic",
    altNames: ["Indian pennywort", "Tiger grass", "Asiatic pennywort", "Brahmi gotu kola"],
    description: "Used in both Ayurvedic and Traditional Chinese Medicine, gotu kola is valued for cognitive enhancement, wound healing, and circulatory support.",
    uses: ["Cognitive function", "Anxiety", "Wound healing", "Circulation", "Collagen synthesis"],
    conditions: ["mind-cognition", "stress-mood", "heart-circulation"], papers: [],
  },
  {
    id: 30, name: "Maca", latinName: "Lepidium meyenii",
    family: "Brassicaceae", origin: "Peru (Andes)", partUsed: "Root", category: "Adaptogen",
    altNames: ["Peruvian ginseng", "Maka", "Maino", "Ayak chichira"],
    description: "A root vegetable from the high Andes of Peru, traditionally used for energy, fertility, and hormonal balance across both sexes.",
    uses: ["Energy", "Fertility", "Hormonal balance", "Sexual function", "Menopausal symptoms"],
    conditions: ["performance", "women-health", "metabolic"], papers: [],
  },
  {
    id: 31, name: "Saw Palmetto", latinName: "Serenoa repens",
    family: "Arecaceae", origin: "Southeastern United States", partUsed: "Berries", category: "Men's Health",
    altNames: ["Sabal palm", "Dwarf palm", "Cabbage palm"],
    description: "A small palm native to the southeastern US, widely studied for prostate health and urinary function in men. One of the most sold herbal supplements in the world.",
    uses: ["Prostate health", "BPH", "Urinary flow", "Testosterone balance", "Male pattern baldness"],
    conditions: ["men-health", "metabolic"], papers: [],
  },
  {
    id: 32, name: "Tribulus", latinName: "Tribulus terrestris",
    family: "Zygophyllaceae", origin: "Southern Europe, Asia, Africa", partUsed: "Fruit, root", category: "Men's Health",
    altNames: ["Puncture vine", "Gokhru", "Caltrop", "Bindii"],
    description: "A flowering plant used across Ayurvedic and traditional Chinese medicine for male vitality, libido, and reproductive health. Also used by athletes for performance support.",
    uses: ["Testosterone support", "Libido", "Male fertility", "Erectile function", "Athletic performance"],
    conditions: ["men-health", "performance"], papers: [],
  },
  {
    id: 33, name: "Pine Pollen", latinName: "Pinus sylvestris",
    family: "Pinaceae", origin: "Europe, Asia", partUsed: "Pollen", category: "Men's Health",
    altNames: ["Scots pine pollen", "Pine tree pollen"],
    description: "The pollen of the Scots pine, one of the few plant sources of phyto-androgens including DHEA and testosterone precursors. Used in traditional Chinese medicine to tonify yang and support male hormonal health.",
    uses: ["Testosterone precursor", "Androgen support", "Prostate health", "Fatigue", "Male hormonal balance"],
    conditions: ["men-health", "performance", "immune"], papers: [],
  },
  {
    id: 34, name: "Calendula", latinName: "Calendula officinalis",
    family: "Asteraceae", origin: "Mediterranean, Southern Europe", partUsed: "Flowers", category: "Skin Care",
    altNames: ["Pot marigold", "Garden marigold", "Goldbloom"],
    description: "Bright orange flowers with a long history in wound care and skin healing. Calendula is anti-inflammatory, antimicrobial, and promotes tissue regeneration — a foundational herb in dermatological herbalism.",
    uses: ["Wound healing", "Eczema", "Dermatitis", "Skin inflammation", "Rashes", "Acne"],
    conditions: ["skin-care", "inflammation", "immune"], papers: [],
  },
  {
    id: 35, name: "Neem", latinName: "Azadirachta indica",
    family: "Meliaceae", origin: "Indian Subcontinent", partUsed: "Leaves, bark, seed oil", category: "Skin Care",
    altNames: ["Indian lilac", "Margosa", "Nimtree", "Muarubaini"],
    description: "A sacred tree in Ayurvedic medicine known as the 'village pharmacy'. Neem's potent antimicrobial and antifungal properties make it one of the most effective botanical treatments for acne, skin infections, and scalp conditions.",
    uses: ["Acne", "Fungal skin infections", "Psoriasis", "Dandruff", "Antimicrobial skin care", "Wound healing"],
    conditions: ["skin-care", "immune", "inflammation"], papers: [],
  },
  {
    id: 36, name: "Rosehip", latinName: "Rosa canina",
    family: "Rosaceae", origin: "Europe, Northwest Africa, Western Asia", partUsed: "Fruit (hip)", category: "Skin Care",
    altNames: ["Dog rose hip", "Wild rose fruit", "Canker rose"],
    description: "The fruit of the wild rose, exceptionally rich in vitamin C and essential fatty acids including tretinoin precursors. Rosehip oil has strong clinical evidence for reducing scars, hyperpigmentation, and fine lines.",
    uses: ["Anti-aging", "Hyperpigmentation", "Scar reduction", "Skin hydration", "UV damage repair", "Collagen synthesis"],
    conditions: ["skin-care", "inflammation", "immune"], papers: [],
  },
];
